version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/bjj-fe"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "maven"
    directory: "/bjj-be"
    schedule:
      interval: "daily"
