name: Dependabot auto-approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Approve & squash
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.draft == false

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check update type
        id: gate
        shell: bash
        run: |
          t="${{ steps.metadata.outputs.update-type }}"
          if [ "$t" = "security" ] || [ "$t" = "version-update:semver-minor" ] || [ "$t" = "version-update:semver-patch" ]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if not allowed
        if: steps.gate.outputs.ok != 'true'
        run: echo "Skipping auto-merge for update type ${{ steps.metadata.outputs.update-type }}"

      - name: Assert GH_TOKEN present
        if: steps.gate.outputs.ok == 'true'
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "GH_TOKEN is EMPTY. Check repository secrets or environment wiring." >&2
            exit 1
          fi

      - name: Approve
        if: steps.gate.outputs.ok == 'true'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: gh pr review --approve "$PR_URL" --body "Auto-approving eligible Dependabot update."

      - name: Enable auto-merge (squash)
        if: steps.gate.outputs.ok == 'true'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: gh pr merge --squash --auto --delete-branch "$PR_URL"
